"""autogenerated by genpy from controller/XbeeData.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class XbeeData(genpy.Message):
  _md5sum = "b7e330524fa79c3fba6bcd72b2bca3fd"
  _type = "controller/XbeeData"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """float32[3] joy_des_angles
uint8 joy_thrust
uint8 flight_mode
"""
  __slots__ = ['joy_des_angles','joy_thrust','flight_mode']
  _slot_types = ['float32[3]','uint8','uint8']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       joy_des_angles,joy_thrust,flight_mode

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(XbeeData, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.joy_des_angles is None:
        self.joy_des_angles = [0.,0.,0.]
      if self.joy_thrust is None:
        self.joy_thrust = 0
      if self.flight_mode is None:
        self.flight_mode = 0
    else:
      self.joy_des_angles = [0.,0.,0.]
      self.joy_thrust = 0
      self.flight_mode = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      buff.write(_struct_3f.pack(*self.joy_des_angles))
      _x = self
      buff.write(_struct_2B.pack(_x.joy_thrust, _x.flight_mode))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(_x))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(_x))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      start = end
      end += 12
      self.joy_des_angles = _struct_3f.unpack(str[start:end])
      _x = self
      start = end
      end += 2
      (_x.joy_thrust, _x.flight_mode,) = _struct_2B.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      buff.write(self.joy_des_angles.tostring())
      _x = self
      buff.write(_struct_2B.pack(_x.joy_thrust, _x.flight_mode))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(_x))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(_x))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      start = end
      end += 12
      self.joy_des_angles = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=3)
      _x = self
      start = end
      end += 2
      (_x.joy_thrust, _x.flight_mode,) = _struct_2B.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_3f = struct.Struct("<3f")
_struct_2B = struct.Struct("<2B")
