// Generated by gencpp from file quad_msgs/MotorCommands.msg
// DO NOT EDIT!


#ifndef QUAD_MSGS_MESSAGE_MOTORCOMMANDS_H
#define QUAD_MSGS_MESSAGE_MOTORCOMMANDS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace quad_msgs
{
template <class ContainerAllocator>
struct MotorCommands_
{
  typedef MotorCommands_<ContainerAllocator> Type;

  MotorCommands_()
    : header()
    , m0(0.0)
    , m1(0.0)
    , m2(0.0)
    , m3(0.0)  {
    }
  MotorCommands_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , m0(0.0)
    , m1(0.0)
    , m2(0.0)
    , m3(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef double _m0_type;
  _m0_type m0;

   typedef double _m1_type;
  _m1_type m1;

   typedef double _m2_type;
  _m2_type m2;

   typedef double _m3_type;
  _m3_type m3;




  typedef boost::shared_ptr< ::quad_msgs::MotorCommands_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::quad_msgs::MotorCommands_<ContainerAllocator> const> ConstPtr;

}; // struct MotorCommands_

typedef ::quad_msgs::MotorCommands_<std::allocator<void> > MotorCommands;

typedef boost::shared_ptr< ::quad_msgs::MotorCommands > MotorCommandsPtr;
typedef boost::shared_ptr< ::quad_msgs::MotorCommands const> MotorCommandsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::quad_msgs::MotorCommands_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::quad_msgs::MotorCommands_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace quad_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'quad_msgs': ['/home/odroid/quad_ws/src/quad_msgs/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::quad_msgs::MotorCommands_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::quad_msgs::MotorCommands_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::quad_msgs::MotorCommands_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::quad_msgs::MotorCommands_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::quad_msgs::MotorCommands_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::quad_msgs::MotorCommands_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::quad_msgs::MotorCommands_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c15c1707ce5f9ebe441818ab35bc9db3";
  }

  static const char* value(const ::quad_msgs::MotorCommands_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc15c1707ce5f9ebeULL;
  static const uint64_t static_value2 = 0x441818ab35bc9db3ULL;
};

template<class ContainerAllocator>
struct DataType< ::quad_msgs::MotorCommands_<ContainerAllocator> >
{
  static const char* value()
  {
    return "quad_msgs/MotorCommands";
  }

  static const char* value(const ::quad_msgs::MotorCommands_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::quad_msgs::MotorCommands_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
float64 m0\n\
float64 m1\n\
float64 m2\n\
float64 m3\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::quad_msgs::MotorCommands_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::quad_msgs::MotorCommands_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.m0);
      stream.next(m.m1);
      stream.next(m.m2);
      stream.next(m.m3);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MotorCommands_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::quad_msgs::MotorCommands_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::quad_msgs::MotorCommands_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "m0: ";
    Printer<double>::stream(s, indent + "  ", v.m0);
    s << indent << "m1: ";
    Printer<double>::stream(s, indent + "  ", v.m1);
    s << indent << "m2: ";
    Printer<double>::stream(s, indent + "  ", v.m2);
    s << indent << "m3: ";
    Printer<double>::stream(s, indent + "  ", v.m3);
  }
};

} // namespace message_operations
} // namespace ros

#endif // QUAD_MSGS_MESSAGE_MOTORCOMMANDS_H
