// Generated by gencpp from file quad_msgs/XbeeData.msg
// DO NOT EDIT!


#ifndef QUAD_MSGS_MESSAGE_XBEEDATA_H
#define QUAD_MSGS_MESSAGE_XBEEDATA_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace quad_msgs
{
template <class ContainerAllocator>
struct XbeeData_
{
  typedef XbeeData_<ContainerAllocator> Type;

  XbeeData_()
    : header()
    , joy_des_angles()
    , joy_thrust(0)
    , flight_mode(0)  {
      joy_des_angles.assign(0.0);
  }
  XbeeData_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , joy_des_angles()
    , joy_thrust(0)
    , flight_mode(0)  {
  (void)_alloc;
      joy_des_angles.assign(0.0);
  }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef boost::array<float, 3>  _joy_des_angles_type;
  _joy_des_angles_type joy_des_angles;

   typedef uint8_t _joy_thrust_type;
  _joy_thrust_type joy_thrust;

   typedef uint8_t _flight_mode_type;
  _flight_mode_type flight_mode;




  typedef boost::shared_ptr< ::quad_msgs::XbeeData_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::quad_msgs::XbeeData_<ContainerAllocator> const> ConstPtr;

}; // struct XbeeData_

typedef ::quad_msgs::XbeeData_<std::allocator<void> > XbeeData;

typedef boost::shared_ptr< ::quad_msgs::XbeeData > XbeeDataPtr;
typedef boost::shared_ptr< ::quad_msgs::XbeeData const> XbeeDataConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::quad_msgs::XbeeData_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::quad_msgs::XbeeData_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace quad_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'quad_msgs': ['/home/odroid/quad_ws/src/quad_msgs/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::quad_msgs::XbeeData_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::quad_msgs::XbeeData_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::quad_msgs::XbeeData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::quad_msgs::XbeeData_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::quad_msgs::XbeeData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::quad_msgs::XbeeData_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::quad_msgs::XbeeData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9e8751e764ae2fdba0ee593ad1928d7c";
  }

  static const char* value(const ::quad_msgs::XbeeData_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9e8751e764ae2fdbULL;
  static const uint64_t static_value2 = 0xa0ee593ad1928d7cULL;
};

template<class ContainerAllocator>
struct DataType< ::quad_msgs::XbeeData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "quad_msgs/XbeeData";
  }

  static const char* value(const ::quad_msgs::XbeeData_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::quad_msgs::XbeeData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
float32[3] joy_des_angles\n\
uint8 joy_thrust\n\
uint8 flight_mode\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::quad_msgs::XbeeData_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::quad_msgs::XbeeData_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.joy_des_angles);
      stream.next(m.joy_thrust);
      stream.next(m.flight_mode);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct XbeeData_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::quad_msgs::XbeeData_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::quad_msgs::XbeeData_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "joy_des_angles[]" << std::endl;
    for (size_t i = 0; i < v.joy_des_angles.size(); ++i)
    {
      s << indent << "  joy_des_angles[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.joy_des_angles[i]);
    }
    s << indent << "joy_thrust: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.joy_thrust);
    s << indent << "flight_mode: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.flight_mode);
  }
};

} // namespace message_operations
} // namespace ros

#endif // QUAD_MSGS_MESSAGE_XBEEDATA_H
