// Generated by gencpp from file xbee/XbeeData.msg
// DO NOT EDIT!


#ifndef XBEE_MESSAGE_XBEEDATA_H
#define XBEE_MESSAGE_XBEEDATA_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace xbee
{
template <class ContainerAllocator>
struct XbeeData_
{
  typedef XbeeData_<ContainerAllocator> Type;

  XbeeData_()
    : joy_des_angles()
    , joy_thrust(0)
    , flight_mode(0)  {
      joy_des_angles.assign(0.0);
  }
  XbeeData_(const ContainerAllocator& _alloc)
    : joy_des_angles()
    , joy_thrust(0)
    , flight_mode(0)  {
      joy_des_angles.assign(0.0);
  }



   typedef boost::array<float, 3>  _joy_des_angles_type;
  _joy_des_angles_type joy_des_angles;

   typedef uint8_t _joy_thrust_type;
  _joy_thrust_type joy_thrust;

   typedef uint8_t _flight_mode_type;
  _flight_mode_type flight_mode;




  typedef boost::shared_ptr< ::xbee::XbeeData_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::xbee::XbeeData_<ContainerAllocator> const> ConstPtr;

}; // struct XbeeData_

typedef ::xbee::XbeeData_<std::allocator<void> > XbeeData;

typedef boost::shared_ptr< ::xbee::XbeeData > XbeeDataPtr;
typedef boost::shared_ptr< ::xbee::XbeeData const> XbeeDataConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::xbee::XbeeData_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::xbee::XbeeData_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace xbee

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'xbee': ['/home/odroid/quad_ws/src/xbee/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::xbee::XbeeData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::xbee::XbeeData_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::xbee::XbeeData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::xbee::XbeeData_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::xbee::XbeeData_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::xbee::XbeeData_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::xbee::XbeeData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b7e330524fa79c3fba6bcd72b2bca3fd";
  }

  static const char* value(const ::xbee::XbeeData_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb7e330524fa79c3fULL;
  static const uint64_t static_value2 = 0xba6bcd72b2bca3fdULL;
};

template<class ContainerAllocator>
struct DataType< ::xbee::XbeeData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "xbee/XbeeData";
  }

  static const char* value(const ::xbee::XbeeData_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::xbee::XbeeData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32[3] joy_des_angles\n\
uint8 joy_thrust\n\
uint8 flight_mode\n\
";
  }

  static const char* value(const ::xbee::XbeeData_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::xbee::XbeeData_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.joy_des_angles);
      stream.next(m.joy_thrust);
      stream.next(m.flight_mode);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct XbeeData_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::xbee::XbeeData_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::xbee::XbeeData_<ContainerAllocator>& v)
  {
    s << indent << "joy_des_angles[]" << std::endl;
    for (size_t i = 0; i < v.joy_des_angles.size(); ++i)
    {
      s << indent << "  joy_des_angles[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.joy_des_angles[i]);
    }
    s << indent << "joy_thrust: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.joy_thrust);
    s << indent << "flight_mode: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.flight_mode);
  }
};

} // namespace message_operations
} // namespace ros

#endif // XBEE_MESSAGE_XBEEDATA_H
