// Generated by gencpp from file controller/MotorCommands.msg
// DO NOT EDIT!


#ifndef CONTROLLER_MESSAGE_MOTORCOMMANDS_H
#define CONTROLLER_MESSAGE_MOTORCOMMANDS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace controller
{
template <class ContainerAllocator>
struct MotorCommands_
{
  typedef MotorCommands_<ContainerAllocator> Type;

  MotorCommands_()
    : m0(0.0)
    , m1(0.0)
    , m2(0.0)
    , m3(0.0)  {
    }
  MotorCommands_(const ContainerAllocator& _alloc)
    : m0(0.0)
    , m1(0.0)
    , m2(0.0)
    , m3(0.0)  {
  (void)_alloc;
    }



   typedef double _m0_type;
  _m0_type m0;

   typedef double _m1_type;
  _m1_type m1;

   typedef double _m2_type;
  _m2_type m2;

   typedef double _m3_type;
  _m3_type m3;




  typedef boost::shared_ptr< ::controller::MotorCommands_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::controller::MotorCommands_<ContainerAllocator> const> ConstPtr;

}; // struct MotorCommands_

typedef ::controller::MotorCommands_<std::allocator<void> > MotorCommands;

typedef boost::shared_ptr< ::controller::MotorCommands > MotorCommandsPtr;
typedef boost::shared_ptr< ::controller::MotorCommands const> MotorCommandsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::controller::MotorCommands_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::controller::MotorCommands_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace controller

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'controller': ['/home/odroid/quad_ws/src/controller/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::controller::MotorCommands_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::controller::MotorCommands_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::controller::MotorCommands_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::controller::MotorCommands_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::controller::MotorCommands_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::controller::MotorCommands_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::controller::MotorCommands_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1beedc517f24add1c43f0ef95fdcfac7";
  }

  static const char* value(const ::controller::MotorCommands_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1beedc517f24add1ULL;
  static const uint64_t static_value2 = 0xc43f0ef95fdcfac7ULL;
};

template<class ContainerAllocator>
struct DataType< ::controller::MotorCommands_<ContainerAllocator> >
{
  static const char* value()
  {
    return "controller/MotorCommands";
  }

  static const char* value(const ::controller::MotorCommands_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::controller::MotorCommands_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 m0\n\
float64 m1\n\
float64 m2\n\
float64 m3\n\
";
  }

  static const char* value(const ::controller::MotorCommands_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::controller::MotorCommands_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.m0);
      stream.next(m.m1);
      stream.next(m.m2);
      stream.next(m.m3);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MotorCommands_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::controller::MotorCommands_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::controller::MotorCommands_<ContainerAllocator>& v)
  {
    s << indent << "m0: ";
    Printer<double>::stream(s, indent + "  ", v.m0);
    s << indent << "m1: ";
    Printer<double>::stream(s, indent + "  ", v.m1);
    s << indent << "m2: ";
    Printer<double>::stream(s, indent + "  ", v.m2);
    s << indent << "m3: ";
    Printer<double>::stream(s, indent + "  ", v.m3);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CONTROLLER_MESSAGE_MOTORCOMMANDS_H
