// Generated by gencpp from file motors/MotorVals.msg
// DO NOT EDIT!


#ifndef MOTORS_MESSAGE_MOTORVALS_H
#define MOTORS_MESSAGE_MOTORVALS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace motors
{
template <class ContainerAllocator>
struct MotorVals_
{
  typedef MotorVals_<ContainerAllocator> Type;

  MotorVals_()
    : num(0)  {
    }
  MotorVals_(const ContainerAllocator& _alloc)
    : num(0)  {
    }



   typedef uint16_t _num_type;
  _num_type num;




  typedef boost::shared_ptr< ::motors::MotorVals_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::motors::MotorVals_<ContainerAllocator> const> ConstPtr;

}; // struct MotorVals_

typedef ::motors::MotorVals_<std::allocator<void> > MotorVals;

typedef boost::shared_ptr< ::motors::MotorVals > MotorValsPtr;
typedef boost::shared_ptr< ::motors::MotorVals const> MotorValsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::motors::MotorVals_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::motors::MotorVals_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace motors

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'motors': ['/home/odroid/quad_ws/src/motors/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::motors::MotorVals_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::motors::MotorVals_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::motors::MotorVals_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::motors::MotorVals_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::motors::MotorVals_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::motors::MotorVals_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::motors::MotorVals_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0285aea93c08847f409c58db5e8d9137";
  }

  static const char* value(const ::motors::MotorVals_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0285aea93c08847fULL;
  static const uint64_t static_value2 = 0x409c58db5e8d9137ULL;
};

template<class ContainerAllocator>
struct DataType< ::motors::MotorVals_<ContainerAllocator> >
{
  static const char* value()
  {
    return "motors/MotorVals";
  }

  static const char* value(const ::motors::MotorVals_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::motors::MotorVals_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint16 num\n\
";
  }

  static const char* value(const ::motors::MotorVals_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::motors::MotorVals_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.num);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct MotorVals_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::motors::MotorVals_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::motors::MotorVals_<ContainerAllocator>& v)
  {
    s << indent << "num: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.num);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MOTORS_MESSAGE_MOTORVALS_H
